# Generated by Django 4.1.5 on 2023-03-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='book',
            name='av_rating',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.URLField(default=None, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='ratings',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.URLField(default='https://www.amazon.com/', max_length=400),
            preserve_default=False,
        ),
    ]
