# Generated by Django 4.1.5 on 2023-03-10 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_name_book_title_book_authors_book_av_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='url',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='av_rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='ratings',
            new_name='ratings_total',
        ),
    ]
