# Generated by Django 4.1.5 on 2023-03-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_url_book_link_rename_av_rating_book_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.JSONField(default={'name': 'napoleon'}),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.URLField(default='https://m.media-amazon.com/images/I/41gIqB7ouXL._SX326_BO1,204,203,200_.jpg', max_length=400),
        ),
        migrations.AlterField(
            model_name='book',
            name='link',
            field=models.URLField(default='https://www.amazon.co.uk/', max_length=400),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.CharField(default=5, max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='ratings_total',
            field=models.CharField(default=10000, max_length=10),
        ),
    ]
